version: 2.1

orbs: 
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4
  heroku: circleci/heroku@2.0.0
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout 
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
        pkg-manager: npm 
      - run: |
          echo "Running tests..."
          npm test
  scan:
    docker:
      - image: cimg/node:16.10
    environment:
        IMAGE_NAME: sitiaminahak/education-space
    steps:
      - checkout
      - setup_remote_docker
      - docker/check
      - run: docker build -t $IMAGE_NAME .
      - snyk/scan:
          severity-threshold: high
          docker-image-name: $IMAGE_NAME
          fail-on-issues: true
  publish:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: sitiaminahak/education-space
          tag: << pipeline.git.tag >>
          #tag: v1.0.1
      - docker/push:
          image: sitiaminahak/education-space
          tag: << pipeline.git.tag >>
          #tag: v1.0.1
  deploy: # Assignment 4.5
    docker:
      - image: cimg/node:16.10
    steps:
      - setup_remote_docker
      - checkout
      - heroku/install
      - run:
          name: Heroku Container Push
          command: |
              heroku container:login
              heroku container:push web -a sitidevops
              heroku container:release web -a sitidevops
  # pull-and-deploy:
  #   docker:
  #     - image: cimg/node:16.10
  #   steps:
  #     - setup_remote_docker
  #     - heroku/install
  #     - docker/pull:
  #         images: sitiaminahak/education-space:v1.0.1
  #     - run:
  #         name: Heroku Container Push
  #         command: |
  #             heroku container:login
  #             docker tag sitiaminahak/education-space:v1.0.1 registry.heroku.com/sitidevops/web
  #             # format --- docker tag <image name from docker hub> registry.heroku.com/<app-name>/web
  #             docker push registry.heroku.com/sitidevops/web
  #             # format --- docker push <registry.heroku.com/<app-name>/web
  #             heroku container:release web -a sitidevops

# workflows: # Assignment 4.6
#   simple_workflow:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build
#       - publish:
#           requires:
#             - test
#           filters:
#             tags:
#               only: /^v.*/
#             branches:
#               ignore: main
#       - deploy:
#           requires:
#             - publish
#           filters:
#             tags:
#               only: /^v.*/ 
#             branches:
#               ignore: main

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - scan:
          requires:
            - test
      - publish:
          requires:
            - scan